[package]
name = "cesa_conn_networker"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cesa_conn_networker"
path = "src/cesa_conn_networker.rs"

[dependencies]
btleplug = "0.11.8"
tokio = { version = "1.50.0", features = ["full"] }
cesa_conn_crypto = { path = "../cesa_conn_crypto" }
tokio-util = "0.7.18"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zeroize = "1.8.2"
snow = "0.10.0"
ml-kem = "0.3.2"

